<?php

    namespace PHPerian\CAIS\Report\Block\Body;

    use \PHPerian\Exceptions;
    use \PHPerian\CAIS\Collection;
    use \PHPerian\CAIS\Interfaces\Attribute as AttributeInterface;

    class Record extends Collection
    {

        protected static $attributeDefinitions = array(
            'submember' => array(
                'type'          => AttributeInterface::INTEGER,
                'start'         => 1,
                'end'           => 3,
                'name'          => 'Submember',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_RIGHT,
                'padding'       => '0',
            ),
            'customer' => array(
                'type'          => AttributeInterface::ALPHANUMERIC,
                'start'         => 4,
                'end'           => 11,
                'name'          => 'Customer ID',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_RIGHT,
                'padding'       => '0',
            ),
            'loan' => array(
                'type'          => AttributeInterface::ALPHANUMERIC,
                'start'         => 12,
                'end'           => 19,
                'name'          => 'Loan ID',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_RIGHT,
                'padding'       => '0',
            ),
            'jointAccount' => array(
                'type'          => AttributeInterface::INTEGER,
                'start'         => 20,
                'end'           => 20,
                'name'          => 'Account Number',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_LEFT,
                'padding'       => ' ',
            ),
            'accountType' => array(
                'type'          => AttributeInterface::INTEGER,
                'start'         => 21,
                'end'           => 22,
                'name'          => 'Account Types',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_RIGHT,
                'padding'       => '0',
            ),
            'startDate' => array(
                'type'          => AttributeInterface::DATE,
                'start'         => 23,
                'end'           => 30,
                'name'          => 'Start Date',
                'default'       => null,
            ),
            'closeDate' => array(
                'type'          => AttributeInterface::DATE,
                'start'         => 31,
                'end'           => 38,
                'name'          => 'Close Date',
                'default'       => null,
            ),
            'monthlyPayment' => array(
                'type'          => AttributeInterface::INTEGER,
                'start'         => 39,
                'end'           => 44,
                'name'          => 'Monthly Payment',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_RIGHT,
                'padding'       => '0',
            ),
            'repaymentPeriod' => array(
                'type'          => AttributeInterface::INTEGER,
                'start'         => 45,
                'end'           => 47,
                'name'          => 'Repayment Period',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_RIGHT,
                'padding'       => '0',
            ),
            'currentBalance' => array(
                'type'          => AttributeInterface::INTEGER,
                'start'         => 48,
                'end'           => 54,
                'name'          => 'Current Balance',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_RIGHT,
                'padding'       => '0',
            ),
            'creditBalanceIndicator' => array(
                'type'          => AttributeInterface::BOOLEAN,
                'start'         => 55,
                'end'           => 55,
                'name'          => 'Credit Balance Indicator',
                'default'       => true,
                'justification' => AttributeInterface::JUSTIFY_LEFT,
                'padding'       => ' ',
                'booleanflags'  => '- ',
            ),
            'accountStatusCode' => array(
                'type'          => AttributeInterface::ALPHANUMERIC,
                'start'         => 56,
                'end'           => 56,
                'name'          => 'Account Status Code',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_LEFT,
                'padding'       => ' ',
            ),
            'specialInstructionIndicator' => array(
                'type'          => AttributeInterface::ALPHA,
                'start'         => 57,
                'end'           => 57,
                'name'          => 'Special Instruction Indicator',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_LEFT,
                'padding'       => ' ',
            ),
            'custom' => array(
                'type'          => AttributeInterface::ALPHANUMERIC,
                'start'         => 58,
                'end'           => 207,
                'name'          => 'Experian Block',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_LEFT,
                'padding'       => ' ',
            ),
            'paymentAmount' => array(
                'type'          => AttributeInterface::INTEGER,
                'start'         => 208,
                'end'           => 213,
                'name'          => 'Payment Amount',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_RIGHT,
                'padding'       => '0',
            ),
            'creditPaymentIndicator' => array(
                'type'          => AttributeInterface::BOOLEAN,
                'start'         => 214,
                'end'           => 214,
                'name'          => 'Credit Payment Indicator',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_LEFT,
                'padding'       => ' ',
                'booleanflags'  => '- ',
            ),
            'previousStatementBalance' => array(
                'type'          => AttributeInterface::INTEGER,
                'start'         => 215,
                'end'           => 220,
                'name'          => 'Account Status Code',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_RIGHT,
                'padding'       => '0',
            ),
            'previousStatementBalanceIndicator' => array(
                'type'          => AttributeInterface::BOOLEAN,
                'start'         => 221,
                'end'           => 221,
                'name'          => 'Previous Statement Balance Indicator',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_LEFT,
                'padding'       => ' ',
                'booleanflags'  => '- ',
            ),
            'numberOfCashAdvances' => array(
                'type'          => AttributeInterface::INTEGER,
                'start'         => 222,
                'end'           => 223,
                'name'          => 'Number of Cash Advances',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_RIGHT,
                'padding'       => '0',
            ),
            'valueOfCashAdvances' => array(
                'type'          => AttributeInterface::INTEGER,
                'start'         => 224,
                'end'           => 229,
                'name'          => 'Value of Cash Advances',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_RIGHT,
                'padding'       => '0',
            ),
            'paymentCode' => array(
                'type'          => AttributeInterface::BOOLEAN,
                'start'         => 230,
                'end'           => 230,
                'name'          => 'Payment Code',
                'default'       => false,
                'justification' => AttributeInterface::JUSTIFY_LEFT,
                'padding'       => ' ',
                'booleanflags'  => 'M ',
            ),
            'promotionActivityFlag' => array(
                'type'          => AttributeInterface::BOOLEAN,
                'start'         => 231,
                'end'           => 231,
                'name'          => 'Promotion Activity Flag',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_LEFT,
                'padding'       => ' ',
                'booleanflags'  => 'Y ',
            ),
            'filler1' => array(
                'type'          => AttributeInterface::READONLY,
                'start'         => 232,
                'end'           => 262,
                'name'          => 'Filler One',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_LEFT,
                'padding'       => ' ',
            ),
            'transientAssociationFlag' => array(
                'type'          => AttributeInterface::BOOLEAN,
                'start'         => 263,
                'end'           => 263,
                'name'          => 'Transient Association Flag',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_LEFT,
                'padding'       => ' ',
                'booleanflags'  => 'T ',
            ),
            'airtimeRetailerFlag' => array(
                'type'          => AttributeInterface::ALPHA,
                'start'         => 264,
                'end'           => 264,
                'name'          => 'Air-time Retailer Flag',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_LEFT,
                'padding'       => ' ',
            ),
            'flagSettings' => array(
                'type'          => AttributeInterface::ALPHA,
                'start'         => 265,
                'end'           => 265,
                'name'          => 'Flag Settings',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_LEFT,
                'padding'       => ' ',
            ),
            'name' => array(
                'type'          => AttributeInterface::ALPHA,
                'start'         => 266,
                'end'           => 304,
                'name'          => 'Customer Name',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_LEFT,
                'padding'       => ' ',
            ),
            'addressLine1' => array(
                'type'          => AttributeInterface::ALPHANUMERIC,
                'start'         => 305,
                'end'           => 336,
                'name'          => 'Address Line 1',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_LEFT,
                'padding'       => ' ',
            ),
            'addressLine2' => array(
                'type'          => AttributeInterface::ALPHANUMERIC,
                'start'         => 337,
                'end'           => 368,
                'name'          => 'Adress Line 2',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_LEFT,
                'padding'       => ' ',
            ),
            'addressLine3' => array(
                'type'          => AttributeInterface::ALPHANUMERIC,
                'start'         => 369,
                'end'           => 400,
                'name'          => 'Address Line 3',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_LEFT,
                'padding'       => ' ',
            ),
            'addressLine4' => array(
                'type'          => AttributeInterface::ALPHANUMERIC,
                'start'         => 401,
                'end'           => 432,
                'name'          => 'Address Line 4',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_LEFT,
                'padding'       => ' ',
            ),
            'postcode' => array(
                'type'          => AttributeInterface::ALPHANUMERIC,
                'start'         => 433,
                'end'           => 440,
                'name'          => 'Postcode',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_LEFT,
                'padding'       => ' ',
            ),
            'creditLimit' => array(
                'type'          => AttributeInterface::INTEGER,
                'start'         => 441,
                'end'           => 447,
                'name'          => 'Account Status Code',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_RIGHT,
                'padding'       => '0',
            ),
            'dateOfBirth' => array(
                'type'          => AttributeInterface::DATE,
                'start'         => 448,
                'end'           => 455,
                'name'          => 'Date of Birth',
                'default'       => null,
            ),
            'filler2' => array(
                'type'          => AttributeInterface::READONLY,
                'start'         => 456,
                'end'           => 456,
                'name'          => 'Filler Two',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_LEFT,
                'padding'       => ' ',
            ),
            'transferredToCollectionAccountFlag' => array(
                'type'          => AttributeInterface::BOOLEAN,
                'start'         => 457,
                'end'           => 457,
                'name'          => 'Transferred to Collection Account?',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_LEFT,
                'padding'       => ' ',
                'booleanflags'  => 'Y ',
            ),
            'balanceType' => array(
                'type'          => AttributeInterface::ALPHA,
                'start'         => 458,
                'end'           => 458,
                'name'          => 'Balance Type',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_LEFT,
                'padding'       => ' ',
            ),
            'creditTurnover' => array(
                'type'          => AttributeInterface::INTEGER,
                'start'         => 459,
                'end'           => 467,
                'name'          => 'Credit Turnover',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_RIGHT,
                'padding'       => '0',
            ),
            'primaryAccountIndicator' => array(
                'type'          => AttributeInterface::ALPHA,
                'start'         => 468,
                'end'           => 468,
                'name'          => 'Primary Account?',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_LEFT,
                'padding'       => ' ',
            ),
            'defaultSatisfactionDate' => array(
                'type'          => AttributeInterface::DATE,
                'start'         => 469,
                'end'           => 476,
                'name'          => 'Default Satisfaction Date',
                'default'       => null,
            ),
            'transactionsFlag' => array(
                'type'          => AttributeInterface::INTEGER,
                'start'         => 477,
                'end'           => 477,
                'name'          => 'Transactions?',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_LEFT,
                'padding'       => ' ',
            ),
            'filler3' => array(
                'type'          => AttributeInterface::READONLY,
                'start'         => 476,
                'end'           => 502,
                'name'          => 'Filler Three',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_LEFT,
                'padding'       => ' ',
            ),
            'originalDefaultBalance' => array(
                'type'          => AttributeInterface::INTEGER,
                'start'         => 503,
                'end'           => 509,
                'name'          => 'Original Default Balance',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_RIGHT,
                'padding'       => '0',
            ),
            'paymentFrequencyIndicator' => array(
                'type'          => AttributeInterface::ALPHA,
                'start'         => 510,
                'end'           => 510,
                'name'          => 'Payment Frequency Indicator',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_LEFT,
                'padding'       => ' ',
            ),
            'newAccountNumber' => array(
                'type'          => AttributeInterface::ALPHANUMERIC,
                'start'         => 511,
                'end'           => 530,
                'name'          => 'New Account Number',
                'default'       => null,
                'justification' => AttributeInterface::JUSTIFY_LEFT,
                'padding'       => ' ',
            ),
        );

    }
